aality_cms_page_admin:
  resource: |
    alias: aality_cms_page.page
    section: admin
    templates: "@SyliusCMSBundle/admin/page"
    grid: aality_cms_page
    redirect: index
  type: sylius.resource
  prefix: admin

aality_cms_page_public:
  path: /{_locale}/page/{slug}
  controller: Aality\SyliusCMSBundle\Controller\PageController::index
