sylius_resource:
    resources:
        app.page:
            classes:
                model: App\AaPageCmsBundle\Entity\Page\Page
services:
    App\AaPageCmsBundle\Controller\PageController:
        autowire: true
        autoconfigure: true
        tags: [ 'controller.service_arguments' ]
        
    App\AaPageCmsBundle\EventSubscriber\AdminMenuSubscriber:
        tags:
            - { name: kernel.event_subscriber }


