sylius_resource:
    resources:
        app.page:
            classes:
                model: App\Bundle\AaPageCmsBundle\Entity\Page\Page
                form: App\Bundle\AaPageCmsBundle\Form\Type\PageType
services:
    App\Bundle\AaPageCmsBundle\Controller\PageController:
        autowire: true
        autoconfigure: true
        tags: [ 'controller.service_arguments' ]
        
    App\Bundle\AaPageCmsBundle\EventSubscriber\AdminMenuSubscriber:
        tags:
            - { name: kernel.event_subscriber }

# config/packages/twig.yaml
twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/src/Bundle/AaPageCmsBundle/templates': AaPageCmsBundle


sylius_grid:
    grids:
        app_admin_page:
            driver:
                name: doctrine/orm
                options:
                    class: App\Bundle\AaPageCmsBundle\Entity\Page\Page
            fields:
                title:
                    type: string
                channel:
                    type: twig
                    label: Canal de vente
                    path: .
                    options:
                        template: '@AaPageCmsBundle/shared/grid/field/channel.html.twig'
                publicUrl:
                    type: twig
                    label: URL finale
                    options:
                        template: '@AaPageCmsBundle/admin/field/public_url.html.twig'
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
