sylius_resource:
    resources:
        app.page:
            classes:
                model: App\Bundle\AaPageCmsBundle\Entity\Page\Page
services:
    App\Bundle\AaPageCmsBundle\Controller\PageController:
        autowire: true
        autoconfigure: true
        tags: [ 'controller.service_arguments' ]
        
    App\Bundle\AaPageCmsBundle\EventSubscriber\AdminMenuSubscriber:
        tags:
            - { name: kernel.event_subscriber }


sylius_grid:
    grids:
        app_admin_page:
            driver:
                name: doctrine/orm
                options:
                    class: App\Bundle\AaPageCmsBundle\Entity\Page\Page
            fields:
                slug:
                    type: string
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
