sylius_resource:
    resources:
        app.page:
            classes:
                model: Aality\SyliusCMSBundle\Entity\Page\Page
                form: Aality\SyliusCMSBundle\Form\Type\PageType
services:
    Aality\SyliusCMSBundle\Controller\PageController:
        autowire: true
        autoconfigure: true
        tags: [ 'controller.service_arguments' ]

    Aality\SyliusCMSBundle\EventSubscriber\AdminMenuSubscriber:
        tags:
            - { name: kernel.event_subscriber }
        arguments:
          [ '@security.helper' ]

# config/packages/twig.yaml
twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/vendor/aality/cms-bundle/templates': SyliusCMSBundle


sylius_grid:
    grids:
        app_admin_page:
            driver:
                name: doctrine/orm
                options:
                    class: Aality\SyliusCMSBundle\Entity\Page\Page
            fields:
                title:
                    type: string
                channel:
                    type: twig
                    label: Canal de vente
                    path: .
                    options:
                        template: '@SyliusCMSBundle/shared/grid/field/channel.html.twig'
                publicUrl:
                    type: twig
                    label: URL finale
                    options:
                        template: '@SyliusCMSBundle/admin/field/public_url.html.twig'
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
