app_page:
  resource: |
    alias: app.page
    section: admin
    templates: "@SyliusCMSBundle/admin/page"
    grid: app_admin_page
    redirect: index
  type: sylius.resource
  prefix: admin

app_page_public:
  path: /{_locale}/page/{slug}
  controller: Aality\SyliusCMSBundle\Controller\PageController::index
